import type { MetadataRoute } from 'next';

/**
 * The web app manifest -- what makes the site installable on a phone home
 * screen and what tells the OS how to open it once it is there.
 *
 * SERVED AT /manifest.webmanifest, NOT /manifest.json. That is Next's own
 * naming for `app/manifest.ts` and it is not configurable; the <link
 * rel="manifest"> in the document head is injected automatically to match, so
 * nothing in app/layout.tsx has to know about it. next.config.mjs rewrites
 * /manifest.json onto it as well, for anything that goes looking under the more
 * familiar name.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Lewa',
    short_name: 'Lewa',
    description: 'School Information System',

    // The school door rather than the dashboard: an installed app is opened
    // cold, by someone who may not have a live session, and the dashboard would
    // only bounce them here anyway. Someone already signed in is redirected on
    // from here by the login page itself.
    start_url: '/school/login',

    /**
     * Explicit even though '/' is what it would default to (the directory the
     * manifest is served from). Scope is what decides whether a link stays
     * inside the installed app or throws the user out into a browser tab, so
     * the app spanning /school, /teacher and /admin is worth stating rather
     * than inheriting.
     */
    scope: '/',

    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#0f2345',
    orientation: 'portrait',

    /**
     * 192 and 512 are the pair Android requires before it will offer to
     * install at all -- 192 is the home screen icon, 512 the splash screen.
     * Generated by scripts/generate-pwa-icons.mjs; see that file for why they
     * are committed rather than built.
     *
     * The iPhone icon is not listed here. iOS ignores manifest icons for the
     * home screen and reads <link rel="apple-touch-icon"> instead, which is in
     * app/layout.tsx.
     */
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
}
